import { db, queryClient } from "../db/client.js";
import { dailyVerses } from "../db/schema.js";

interface DailyVerse {
  dayOfYear: number;
  reference: string;
  text: string;
  versionAbbreviation: string;
}

/**
 * 366 curated daily verses covering both testaments.
 * Themed for encouragement, faith, peace, strength, hope, love, and guidance.
 * All texts are KJV.
 */
const DAILY_VERSES: DailyVerse[] = [
  // JANUARY (Days 1-31) — New Beginnings & God's Faithfulness
  { dayOfYear: 1, reference: "Lamentations 3:22-23", text: "It is of the LORD's mercies that we are not consumed, because his compassions fail not. They are new every morning: great is thy faithfulness.", versionAbbreviation: "KJV" },
  { dayOfYear: 2, reference: "Proverbs 3:5-6", text: "Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.", versionAbbreviation: "KJV" },
  { dayOfYear: 3, reference: "Philippians 4:13", text: "I can do all things through Christ which strengtheneth me.", versionAbbreviation: "KJV" },
  { dayOfYear: 4, reference: "Jeremiah 29:11", text: "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.", versionAbbreviation: "KJV" },
  { dayOfYear: 5, reference: "Romans 8:28", text: "And we know that all things work together for good to them that love God, to them who are the called according to his purpose.", versionAbbreviation: "KJV" },
  { dayOfYear: 6, reference: "Isaiah 41:10", text: "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.", versionAbbreviation: "KJV" },
  { dayOfYear: 7, reference: "Psalm 23:1", text: "The LORD is my shepherd; I shall not want.", versionAbbreviation: "KJV" },
  { dayOfYear: 8, reference: "Joshua 1:9", text: "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.", versionAbbreviation: "KJV" },
  { dayOfYear: 9, reference: "Psalm 46:1", text: "God is our refuge and strength, a very present help in trouble.", versionAbbreviation: "KJV" },
  { dayOfYear: 10, reference: "Isaiah 40:31", text: "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.", versionAbbreviation: "KJV" },
  { dayOfYear: 11, reference: "Psalm 37:4", text: "Delight thyself also in the LORD; and he shall give thee the desires of thine heart.", versionAbbreviation: "KJV" },
  { dayOfYear: 12, reference: "Matthew 11:28", text: "Come unto me, all ye that labour and are heavy laden, and I will give you rest.", versionAbbreviation: "KJV" },
  { dayOfYear: 13, reference: "Romans 8:38-39", text: "For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come, Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord.", versionAbbreviation: "KJV" },
  { dayOfYear: 14, reference: "Psalm 27:1", text: "The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?", versionAbbreviation: "KJV" },
  { dayOfYear: 15, reference: "2 Timothy 1:7", text: "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.", versionAbbreviation: "KJV" },
  { dayOfYear: 16, reference: "Psalm 119:105", text: "Thy word is a lamp unto my feet, and a light unto my path.", versionAbbreviation: "KJV" },
  { dayOfYear: 17, reference: "Philippians 4:6-7", text: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God. And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.", versionAbbreviation: "KJV" },
  { dayOfYear: 18, reference: "Hebrews 11:1", text: "Now faith is the substance of things hoped for, the evidence of things not seen.", versionAbbreviation: "KJV" },
  { dayOfYear: 19, reference: "Psalm 34:8", text: "O taste and see that the LORD is good: blessed is the man that trusteth in him.", versionAbbreviation: "KJV" },
  { dayOfYear: 20, reference: "Isaiah 26:3", text: "Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee.", versionAbbreviation: "KJV" },
  { dayOfYear: 21, reference: "Romans 12:2", text: "And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God.", versionAbbreviation: "KJV" },
  { dayOfYear: 22, reference: "Psalm 91:1-2", text: "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty. I will say of the LORD, He is my refuge and my fortress: my God; in him will I trust.", versionAbbreviation: "KJV" },
  { dayOfYear: 23, reference: "John 3:16", text: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.", versionAbbreviation: "KJV" },
  { dayOfYear: 24, reference: "Psalm 139:14", text: "I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works; and that my soul knoweth right well.", versionAbbreviation: "KJV" },
  { dayOfYear: 25, reference: "Galatians 5:22-23", text: "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith, Meekness, temperance: against such there is no law.", versionAbbreviation: "KJV" },
  { dayOfYear: 26, reference: "Psalm 121:1-2", text: "I will lift up mine eyes unto the hills, from whence cometh my help. My help cometh from the LORD, which made heaven and earth.", versionAbbreviation: "KJV" },
  { dayOfYear: 27, reference: "Ephesians 2:8-9", text: "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God: Not of works, lest any man should boast.", versionAbbreviation: "KJV" },
  { dayOfYear: 28, reference: "Psalm 23:4", text: "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.", versionAbbreviation: "KJV" },
  { dayOfYear: 29, reference: "Matthew 6:33", text: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.", versionAbbreviation: "KJV" },
  { dayOfYear: 30, reference: "1 Corinthians 13:4-5", text: "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up, Doth not behave itself unseemly, seeketh not her own, is not easily provoked, thinketh no evil;", versionAbbreviation: "KJV" },
  { dayOfYear: 31, reference: "Psalm 55:22", text: "Cast thy burden upon the LORD, and he shall sustain thee: he shall never suffer the righteous to be moved.", versionAbbreviation: "KJV" },

  // FEBRUARY (Days 32-59) — Love & Grace
  { dayOfYear: 32, reference: "1 John 4:19", text: "We love him, because he first loved us.", versionAbbreviation: "KJV" },
  { dayOfYear: 33, reference: "Romans 5:8", text: "But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us.", versionAbbreviation: "KJV" },
  { dayOfYear: 34, reference: "1 Corinthians 13:13", text: "And now abideth faith, hope, charity, these three; but the greatest of these is charity.", versionAbbreviation: "KJV" },
  { dayOfYear: 35, reference: "John 15:13", text: "Greater love hath no man than this, that a man lay down his life for his friends.", versionAbbreviation: "KJV" },
  { dayOfYear: 36, reference: "1 John 4:8", text: "He that loveth not knoweth not God; for God is love.", versionAbbreviation: "KJV" },
  { dayOfYear: 37, reference: "Ephesians 3:17-19", text: "That Christ may dwell in your hearts by faith; that ye, being rooted and grounded in love, May be able to comprehend with all saints what is the breadth, and length, and depth, and height; And to know the love of Christ, which passeth knowledge, that ye might be filled with all the fulness of God.", versionAbbreviation: "KJV" },
  { dayOfYear: 38, reference: "Song of Solomon 8:7", text: "Many waters cannot quench love, neither can the floods drown it: if a man would give all the substance of his house for love, it would utterly be contemned.", versionAbbreviation: "KJV" },
  { dayOfYear: 39, reference: "1 Peter 4:8", text: "And above all things have fervent charity among yourselves: for charity shall cover the multitude of sins.", versionAbbreviation: "KJV" },
  { dayOfYear: 40, reference: "Colossians 3:14", text: "And above all these things put on charity, which is the bond of perfectness.", versionAbbreviation: "KJV" },
  { dayOfYear: 41, reference: "John 13:34", text: "A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another.", versionAbbreviation: "KJV" },
  { dayOfYear: 42, reference: "Romans 13:10", text: "Love worketh no ill to his neighbour: therefore love is the fulfilling of the law.", versionAbbreviation: "KJV" },
  { dayOfYear: 43, reference: "1 Corinthians 16:14", text: "Let all your things be done with charity.", versionAbbreviation: "KJV" },
  { dayOfYear: 44, reference: "Psalm 86:15", text: "But thou, O Lord, art a God full of compassion, and gracious, longsuffering, and plenteous in mercy and truth.", versionAbbreviation: "KJV" },
  { dayOfYear: 45, reference: "Zephaniah 3:17", text: "The LORD thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy; he will rest in his love, he will joy over thee with singing.", versionAbbreviation: "KJV" },
  { dayOfYear: 46, reference: "1 John 3:1", text: "Behold, what manner of love the Father hath bestowed upon us, that we should be called the sons of God: therefore the world knoweth us not, because it knew him not.", versionAbbreviation: "KJV" },
  { dayOfYear: 47, reference: "Deuteronomy 7:9", text: "Know therefore that the LORD thy God, he is God, the faithful God, which keepeth covenant and mercy with them that love him and keep his commandments to a thousand generations;", versionAbbreviation: "KJV" },
  { dayOfYear: 48, reference: "Psalm 136:1", text: "O give thanks unto the LORD; for he is good: for his mercy endureth for ever.", versionAbbreviation: "KJV" },
  { dayOfYear: 49, reference: "Titus 3:4-5", text: "But after that the kindness and love of God our Saviour toward man appeared, Not by works of righteousness which we have done, but according to his mercy he saved us, by the washing of regeneration, and renewing of the Holy Ghost;", versionAbbreviation: "KJV" },
  { dayOfYear: 50, reference: "1 John 4:16", text: "And we have known and believed the love that God hath to us. God is love; and he that dwelleth in love dwelleth in God, and God in him.", versionAbbreviation: "KJV" },
  { dayOfYear: 51, reference: "Psalm 103:8", text: "The LORD is merciful and gracious, slow to anger, and plenteous in mercy.", versionAbbreviation: "KJV" },
  { dayOfYear: 52, reference: "Ephesians 4:2", text: "With all lowliness and meekness, with longsuffering, forbearing one another in love;", versionAbbreviation: "KJV" },
  { dayOfYear: 53, reference: "Micah 6:8", text: "He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?", versionAbbreviation: "KJV" },
  { dayOfYear: 54, reference: "1 John 4:11", text: "Beloved, if God so loved us, we ought also to love one another.", versionAbbreviation: "KJV" },
  { dayOfYear: 55, reference: "Romans 12:9", text: "Let love be without dissimulation. Abhor that which is evil; cleave to that which is good.", versionAbbreviation: "KJV" },
  { dayOfYear: 56, reference: "Psalm 145:8-9", text: "The LORD is gracious, and full of compassion; slow to anger, and of great mercy. The LORD is good to all: and his tender mercies are over all his works.", versionAbbreviation: "KJV" },
  { dayOfYear: 57, reference: "Mark 12:30-31", text: "And thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind, and with all thy strength: this is the first commandment. And the second is like, namely this, Thou shalt love thy neighbour as thyself. There is none other commandment greater than these.", versionAbbreviation: "KJV" },
  { dayOfYear: 58, reference: "2 Corinthians 13:14", text: "The grace of the Lord Jesus Christ, and the love of God, and the communion of the Holy Ghost, be with you all. Amen.", versionAbbreviation: "KJV" },
  { dayOfYear: 59, reference: "Psalm 63:3", text: "Because thy lovingkindness is better than life, my lips shall praise thee.", versionAbbreviation: "KJV" },

  // MARCH (Days 60-90) — Strength & Courage
  { dayOfYear: 60, reference: "Deuteronomy 31:6", text: "Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee.", versionAbbreviation: "KJV" },
  { dayOfYear: 61, reference: "Psalm 18:2", text: "The LORD is my rock, and my fortress, and my deliverer; my God, my strength, in whom I will trust; my buckler, and the horn of my salvation, and my high tower.", versionAbbreviation: "KJV" },
  { dayOfYear: 62, reference: "Nehemiah 8:10", text: "Then he said unto them, Go your way, eat the fat, and drink the sweet, and send portions unto them for whom nothing is prepared: for this day is holy unto our Lord: neither be ye sorry; for the joy of the LORD is your strength.", versionAbbreviation: "KJV" },
  { dayOfYear: 63, reference: "Psalm 28:7", text: "The LORD is my strength and my shield; my heart trusted in him, and I am helped: therefore my heart greatly rejoiceth; and with my song will I praise him.", versionAbbreviation: "KJV" },
  { dayOfYear: 64, reference: "Isaiah 40:29", text: "He giveth power to the faint; and to them that have no might he increaseth strength.", versionAbbreviation: "KJV" },
  { dayOfYear: 65, reference: "2 Corinthians 12:9", text: "And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness. Most gladly therefore will I rather glory in my infirmities, that the power of Christ may rest upon me.", versionAbbreviation: "KJV" },
  { dayOfYear: 66, reference: "Psalm 73:26", text: "My flesh and my heart faileth: but God is the strength of my heart, and my portion for ever.", versionAbbreviation: "KJV" },
  { dayOfYear: 67, reference: "Ephesians 6:10", text: "Finally, my brethren, be strong in the Lord, and in the power of his might.", versionAbbreviation: "KJV" },
  { dayOfYear: 68, reference: "Psalm 138:3", text: "In the day when I cried thou answeredst me, and strengthenedst me with strength in my soul.", versionAbbreviation: "KJV" },
  { dayOfYear: 69, reference: "Isaiah 12:2", text: "Behold, God is my salvation; I will trust, and not be afraid: for the LORD JEHOVAH is my strength and my song; he also is become my salvation.", versionAbbreviation: "KJV" },
  { dayOfYear: 70, reference: "Habakkuk 3:19", text: "The LORD God is my strength, and he will make my feet like hinds' feet, and he will make me to walk upon mine high places.", versionAbbreviation: "KJV" },
  { dayOfYear: 71, reference: "Psalm 31:24", text: "Be of good courage, and he shall strengthen your heart, all ye that hope in the LORD.", versionAbbreviation: "KJV" },
  { dayOfYear: 72, reference: "1 Chronicles 16:11", text: "Seek the LORD and his strength, seek his face continually.", versionAbbreviation: "KJV" },
  { dayOfYear: 73, reference: "Psalm 29:11", text: "The LORD will give strength unto his people; the LORD will bless his people with peace.", versionAbbreviation: "KJV" },
  { dayOfYear: 74, reference: "Colossians 1:11", text: "Strengthened with all might, according to his glorious power, unto all patience and longsuffering with joyfulness;", versionAbbreviation: "KJV" },
  { dayOfYear: 75, reference: "Psalm 118:14", text: "The LORD is my strength and song, and is become my salvation.", versionAbbreviation: "KJV" },
  { dayOfYear: 76, reference: "2 Samuel 22:33", text: "God is my strength and power: and he maketh my way perfect.", versionAbbreviation: "KJV" },
  { dayOfYear: 77, reference: "Psalm 46:10", text: "Be still, and know that I am God: I will be exalted among the heathen, I will be exalted in the earth.", versionAbbreviation: "KJV" },
  { dayOfYear: 78, reference: "Isaiah 41:13", text: "For I the LORD thy God will hold thy right hand, saying unto thee, Fear not; I will help thee.", versionAbbreviation: "KJV" },
  { dayOfYear: 79, reference: "Psalm 27:14", text: "Wait on the LORD: be of good courage, and he shall strengthen thine heart: wait, I say, on the LORD.", versionAbbreviation: "KJV" },
  { dayOfYear: 80, reference: "Philippians 4:19", text: "But my God shall supply all your need according to his riches in glory by Christ Jesus.", versionAbbreviation: "KJV" },
  { dayOfYear: 81, reference: "Psalm 16:8", text: "I have set the LORD always before me: because he is at my right hand, I shall not be moved.", versionAbbreviation: "KJV" },
  { dayOfYear: 82, reference: "2 Chronicles 20:15", text: "And he said, Hearken ye, all Judah, and ye inhabitants of Jerusalem, and thou king Jehoshaphat, Thus saith the LORD unto you, Be not afraid nor dismayed by reason of this great multitude; for the battle is not yours, but God's.", versionAbbreviation: "KJV" },
  { dayOfYear: 83, reference: "Psalm 34:17", text: "The righteous cry, and the LORD heareth, and delivereth them out of all their troubles.", versionAbbreviation: "KJV" },
  { dayOfYear: 84, reference: "Isaiah 54:17", text: "No weapon that is formed against thee shall prosper; and every tongue that shall rise against thee in judgment thou shalt condemn. This is the heritage of the servants of the LORD, and their righteousness is of me, saith the LORD.", versionAbbreviation: "KJV" },
  { dayOfYear: 85, reference: "Psalm 62:6-7", text: "He only is my rock and my salvation: he is my defence; I shall not be moved. In God is my salvation and my glory: the rock of my strength, and my refuge, is in God.", versionAbbreviation: "KJV" },
  { dayOfYear: 86, reference: "1 Corinthians 15:57", text: "But thanks be to God, which giveth us the victory through our Lord Jesus Christ.", versionAbbreviation: "KJV" },
  { dayOfYear: 87, reference: "Psalm 40:1-2", text: "I waited patiently for the LORD; and he inclined unto me, and heard my cry. He brought me up also out of an horrible pit, out of the miry clay, and set my feet upon a rock, and established my goings.", versionAbbreviation: "KJV" },
  { dayOfYear: 88, reference: "James 1:12", text: "Blessed is the man that endureth temptation: for when he is tried, he shall receive the crown of life, which the Lord hath promised to them that love him.", versionAbbreviation: "KJV" },
  { dayOfYear: 89, reference: "Psalm 144:1", text: "Blessed be the LORD my strength, which teacheth my hands to war, and my fingers to fight:", versionAbbreviation: "KJV" },
  { dayOfYear: 90, reference: "Romans 8:31", text: "What shall we then say to these things? If God be for us, who can be against us?", versionAbbreviation: "KJV" },

  // APRIL (Days 91-120) — Hope & Promise
  { dayOfYear: 91, reference: "Romans 15:13", text: "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.", versionAbbreviation: "KJV" },
  { dayOfYear: 92, reference: "Hebrews 6:19", text: "Which hope we have as an anchor of the soul, both sure and stedfast, and which entereth into that within the veil;", versionAbbreviation: "KJV" },
  { dayOfYear: 93, reference: "Psalm 42:11", text: "Why art thou cast down, O my soul? and why art thou disquieted within me? hope thou in God: for I shall yet praise him, who is the health of my countenance, and my God.", versionAbbreviation: "KJV" },
  { dayOfYear: 94, reference: "Jeremiah 17:7", text: "Blessed is the man that trusteth in the LORD, and whose hope the LORD is.", versionAbbreviation: "KJV" },
  { dayOfYear: 95, reference: "Romans 5:3-4", text: "And not only so, but we glory in tribulations also: knowing that tribulation worketh patience; And patience, experience; and experience, hope:", versionAbbreviation: "KJV" },
  { dayOfYear: 96, reference: "Psalm 33:18", text: "Behold, the eye of the LORD is upon them that fear him, upon them that hope in his mercy;", versionAbbreviation: "KJV" },
  { dayOfYear: 97, reference: "1 Peter 1:3", text: "Blessed be the God and Father of our Lord Jesus Christ, which according to his abundant mercy hath begotten us again unto a lively hope by the resurrection of Jesus Christ from the dead,", versionAbbreviation: "KJV" },
  { dayOfYear: 98, reference: "Psalm 130:5", text: "I wait for the LORD, my soul doth wait, and in his word do I hope.", versionAbbreviation: "KJV" },
  { dayOfYear: 99, reference: "Isaiah 40:31", text: "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.", versionAbbreviation: "KJV" },
  { dayOfYear: 100, reference: "Psalm 71:14", text: "But I will hope continually, and will yet praise thee more and more.", versionAbbreviation: "KJV" },
  { dayOfYear: 101, reference: "Hebrews 10:23", text: "Let us hold fast the profession of our faith without wavering; (for he is faithful that promised;)", versionAbbreviation: "KJV" },
  { dayOfYear: 102, reference: "Psalm 62:5", text: "My soul, wait thou only upon God; for my expectation is from him.", versionAbbreviation: "KJV" },
  { dayOfYear: 103, reference: "Isaiah 43:19", text: "Behold, I will do a new thing; now it shall spring forth; shall ye not know it? I will even make a way in the wilderness, and rivers in the desert.", versionAbbreviation: "KJV" },
  { dayOfYear: 104, reference: "Psalm 147:11", text: "The LORD taketh pleasure in them that fear him, in those that hope in his mercy.", versionAbbreviation: "KJV" },
  { dayOfYear: 105, reference: "2 Corinthians 4:16-17", text: "For which cause we faint not; but though our outward man perish, yet the inward man is renewed day by day. For our light affliction, which is but for a moment, worketh for us a far more exceeding and eternal weight of glory;", versionAbbreviation: "KJV" },
  { dayOfYear: 106, reference: "Psalm 39:7", text: "And now, Lord, what wait I for? my hope is in thee.", versionAbbreviation: "KJV" },
  { dayOfYear: 107, reference: "Isaiah 49:23", text: "And kings shall be thy nursing fathers, and their queens thy nursing mothers: they shall bow down to thee with their face toward the earth, and lick up the dust of thy feet; and thou shalt know that I am the LORD: for they shall not be ashamed that wait for me.", versionAbbreviation: "KJV" },
  { dayOfYear: 108, reference: "Psalm 119:114", text: "Thou art my hiding place and my shield: I hope in thy word.", versionAbbreviation: "KJV" },
  { dayOfYear: 109, reference: "Revelation 21:4", text: "And God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying, neither shall there be any more pain: for the former things are passed away.", versionAbbreviation: "KJV" },
  { dayOfYear: 110, reference: "Psalm 25:5", text: "Lead me in thy truth, and teach me: for thou art the God of my salvation; on thee do I wait all the day.", versionAbbreviation: "KJV" },
  { dayOfYear: 111, reference: "2 Peter 3:9", text: "The Lord is not slack concerning his promise, as some men count slackness; but is longsuffering to us-ward, not willing that any should perish, but that all should come to repentance.", versionAbbreviation: "KJV" },
  { dayOfYear: 112, reference: "Psalm 31:14-15", text: "But I trusted in thee, O LORD: I said, Thou art my God. My times are in thy hand: deliver me from the hand of mine enemies, and from them that persecute me.", versionAbbreviation: "KJV" },
  { dayOfYear: 113, reference: "Isaiah 55:11", text: "So shall my word be that goeth forth out of my mouth: it shall not return unto me void, but it shall accomplish that which I please, and it shall prosper in the thing whereto I sent it.", versionAbbreviation: "KJV" },
  { dayOfYear: 114, reference: "Psalm 9:9-10", text: "The LORD also will be a refuge for the oppressed, a refuge in times of trouble. And they that know thy name will put their trust in thee: for thou, LORD, hast not forsaken them that seek thee.", versionAbbreviation: "KJV" },
  { dayOfYear: 115, reference: "Hebrews 13:8", text: "Jesus Christ the same yesterday, and to day, and for ever.", versionAbbreviation: "KJV" },
  { dayOfYear: 116, reference: "Psalm 37:7", text: "Rest in the LORD, and wait patiently for him: fret not thyself because of him who prospereth in his way, because of the man who bringeth wicked devices to pass.", versionAbbreviation: "KJV" },
  { dayOfYear: 117, reference: "2 Corinthians 1:3-4", text: "Blessed be God, even the Father of our Lord Jesus Christ, the Father of mercies, and the God of all comfort; Who comforteth us in all our tribulation, that we may be able to comfort them which are in any trouble, by the comfort wherewith we ourselves are comforted of God.", versionAbbreviation: "KJV" },
  { dayOfYear: 118, reference: "Psalm 46:5", text: "God is in the midst of her; she shall not be moved: God shall help her, and that right early.", versionAbbreviation: "KJV" },
  { dayOfYear: 119, reference: "Isaiah 30:18", text: "And therefore will the LORD wait, that he may be gracious unto you, and therefore will he be exalted, that he may have mercy upon you: for the LORD is a God of judgment: blessed are all they that wait for him.", versionAbbreviation: "KJV" },
  { dayOfYear: 120, reference: "Psalm 23:6", text: "Surely goodness and mercy shall follow me all the days of my life: and I will dwell in the house of the LORD for ever.", versionAbbreviation: "KJV" },

  // MAY (Days 121-151) — Guidance & Wisdom
  { dayOfYear: 121, reference: "James 1:5", text: "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.", versionAbbreviation: "KJV" },
  { dayOfYear: 122, reference: "Proverbs 2:6", text: "For the LORD giveth wisdom: out of his mouth cometh knowledge and understanding.", versionAbbreviation: "KJV" },
  { dayOfYear: 123, reference: "Psalm 32:8", text: "I will instruct thee and teach thee in the way which thou shalt go: I will guide thee with mine eye.", versionAbbreviation: "KJV" },
  { dayOfYear: 124, reference: "Proverbs 16:3", text: "Commit thy works unto the LORD, and thy thoughts shall be established.", versionAbbreviation: "KJV" },
  { dayOfYear: 125, reference: "Isaiah 58:11", text: "And the LORD shall guide thee continually, and satisfy thy soul in drought, and make fat thy bones: and thou shalt be like a watered garden, and like a spring of water, whose waters fail not.", versionAbbreviation: "KJV" },
  { dayOfYear: 126, reference: "Proverbs 4:7", text: "Wisdom is the principal thing; therefore get wisdom: and with all thy getting get understanding.", versionAbbreviation: "KJV" },
  { dayOfYear: 127, reference: "Psalm 48:14", text: "For this God is our God for ever and ever: he will be our guide even unto death.", versionAbbreviation: "KJV" },
  { dayOfYear: 128, reference: "Proverbs 11:14", text: "Where no counsel is, the people fall: but in the multitude of counsellors there is safety.", versionAbbreviation: "KJV" },
  { dayOfYear: 129, reference: "John 16:13", text: "Howbeit when he, the Spirit of truth, is come, he will guide you into all truth: for he shall not speak of himself; but whatsoever he shall hear, that shall he speak: and he will shew you things to come.", versionAbbreviation: "KJV" },
  { dayOfYear: 130, reference: "Proverbs 19:21", text: "There are many devices in a man's heart; nevertheless the counsel of the LORD, that shall stand.", versionAbbreviation: "KJV" },
  { dayOfYear: 131, reference: "Psalm 25:9", text: "The meek will he guide in judgment: and the meek will he teach his way.", versionAbbreviation: "KJV" },
  { dayOfYear: 132, reference: "Proverbs 3:13", text: "Happy is the man that findeth wisdom, and the man that getteth understanding.", versionAbbreviation: "KJV" },
  { dayOfYear: 133, reference: "Psalm 143:10", text: "Teach me to do thy will; for thou art my God: thy spirit is good; lead me into the land of uprightness.", versionAbbreviation: "KJV" },
  { dayOfYear: 134, reference: "Proverbs 16:9", text: "A man's heart deviseth his way: but the LORD directeth his steps.", versionAbbreviation: "KJV" },
  { dayOfYear: 135, reference: "John 14:26", text: "But the Comforter, which is the Holy Ghost, whom the Father will send in my name, he shall teach you all things, and bring all things to your remembrance, whatsoever I have said unto you.", versionAbbreviation: "KJV" },
  { dayOfYear: 136, reference: "Proverbs 9:10", text: "The fear of the LORD is the beginning of wisdom: and the knowledge of the holy is understanding.", versionAbbreviation: "KJV" },
  { dayOfYear: 137, reference: "Psalm 119:133", text: "Order my steps in thy word: and let not any iniquity have dominion over me.", versionAbbreviation: "KJV" },
  { dayOfYear: 138, reference: "Proverbs 15:22", text: "Without counsel purposes are disappointed: but in the multitude of counsellors they are established.", versionAbbreviation: "KJV" },
  { dayOfYear: 139, reference: "Isaiah 30:21", text: "And thine ears shall hear a word behind thee, saying, This is the way, walk ye in it, when ye turn to the right hand, and when ye turn to the left.", versionAbbreviation: "KJV" },
  { dayOfYear: 140, reference: "Proverbs 1:7", text: "The fear of the LORD is the beginning of knowledge: but fools despise wisdom and instruction.", versionAbbreviation: "KJV" },
  { dayOfYear: 141, reference: "Psalm 37:23", text: "The steps of a good man are ordered by the LORD: and he delighteth in his way.", versionAbbreviation: "KJV" },
  { dayOfYear: 142, reference: "Proverbs 4:11", text: "I have taught thee in the way of wisdom; I have led thee in right paths.", versionAbbreviation: "KJV" },
  { dayOfYear: 143, reference: "Psalm 25:4", text: "Shew me thy ways, O LORD; teach me thy paths.", versionAbbreviation: "KJV" },
  { dayOfYear: 144, reference: "Proverbs 22:6", text: "Train up a child in the way he should go: and when he is old, he will not depart from it.", versionAbbreviation: "KJV" },
  { dayOfYear: 145, reference: "Psalm 73:24", text: "Thou shalt guide me with thy counsel, and afterward receive me to glory.", versionAbbreviation: "KJV" },
  { dayOfYear: 146, reference: "Proverbs 20:24", text: "Man's goings are of the LORD; how can a man then understand his own way?", versionAbbreviation: "KJV" },
  { dayOfYear: 147, reference: "John 8:12", text: "Then spake Jesus again unto them, saying, I am the light of the world: he that followeth me shall not walk in darkness, but shall have the light of life.", versionAbbreviation: "KJV" },
  { dayOfYear: 148, reference: "Proverbs 8:11", text: "For wisdom is better than rubies; and all the things that may be desired are not to be compared to it.", versionAbbreviation: "KJV" },
  { dayOfYear: 149, reference: "Psalm 119:35", text: "Make me to go in the path of thy commandments; for therein do I delight.", versionAbbreviation: "KJV" },
  { dayOfYear: 150, reference: "Proverbs 3:21-22", text: "My son, let not them depart from thine eyes: keep sound wisdom and discretion: So shall they be life unto thy soul, and grace to thy neck.", versionAbbreviation: "KJV" },
  { dayOfYear: 151, reference: "Psalm 16:11", text: "Thou wilt shew me the path of life: in thy presence is fulness of joy; at thy right hand there are pleasures for evermore.", versionAbbreviation: "KJV" },

  // JUNE (Days 152-181) — Peace & Rest
  { dayOfYear: 152, reference: "John 14:27", text: "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.", versionAbbreviation: "KJV" },
  { dayOfYear: 153, reference: "Isaiah 26:3", text: "Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee.", versionAbbreviation: "KJV" },
  { dayOfYear: 154, reference: "Psalm 4:8", text: "I will both lay me down in peace, and sleep: for thou, LORD, only makest me dwell in safety.", versionAbbreviation: "KJV" },
  { dayOfYear: 155, reference: "Colossians 3:15", text: "And let the peace of God rule in your hearts, to the which also ye are called in one body; and be ye thankful.", versionAbbreviation: "KJV" },
  { dayOfYear: 156, reference: "Psalm 29:11", text: "The LORD will give strength unto his people; the LORD will bless his people with peace.", versionAbbreviation: "KJV" },
  { dayOfYear: 157, reference: "Matthew 11:28-29", text: "Come unto me, all ye that labour and are heavy laden, and I will give you rest. Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls.", versionAbbreviation: "KJV" },
  { dayOfYear: 158, reference: "Psalm 85:8", text: "I will hear what God the LORD will speak: for he will speak peace unto his people, and to his saints: but let them not turn again to folly.", versionAbbreviation: "KJV" },
  { dayOfYear: 159, reference: "Romans 14:17", text: "For the kingdom of God is not meat and drink; but righteousness, and peace, and joy in the Holy Ghost.", versionAbbreviation: "KJV" },
  { dayOfYear: 160, reference: "Psalm 37:11", text: "But the meek shall inherit the earth; and shall delight themselves in the abundance of peace.", versionAbbreviation: "KJV" },
  { dayOfYear: 161, reference: "Isaiah 32:17", text: "And the work of righteousness shall be peace; and the effect of righteousness quietness and assurance for ever.", versionAbbreviation: "KJV" },
  { dayOfYear: 162, reference: "Psalm 119:165", text: "Great peace have they which love thy law: and nothing shall offend them.", versionAbbreviation: "KJV" },
  { dayOfYear: 163, reference: "2 Thessalonians 3:16", text: "Now the Lord of peace himself give you peace always by all means. The Lord be with you all.", versionAbbreviation: "KJV" },
  { dayOfYear: 164, reference: "Psalm 23:2-3", text: "He maketh me to lie down in green pastures: he leadeth me beside the still waters. He restoreth my soul: he leadeth me in the paths of righteousness for his name's sake.", versionAbbreviation: "KJV" },
  { dayOfYear: 165, reference: "Numbers 6:24-26", text: "The LORD bless thee, and keep thee: The LORD make his face shine upon thee, and be gracious unto thee: The LORD lift up his countenance upon thee, and give thee peace.", versionAbbreviation: "KJV" },
  { dayOfYear: 166, reference: "Psalm 34:14", text: "Depart from evil, and do good; seek peace, and pursue it.", versionAbbreviation: "KJV" },
  { dayOfYear: 167, reference: "John 16:33", text: "These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world.", versionAbbreviation: "KJV" },
  { dayOfYear: 168, reference: "Psalm 3:5", text: "I laid me down and slept; I awaked; for the LORD sustained me.", versionAbbreviation: "KJV" },
  { dayOfYear: 169, reference: "Isaiah 57:2", text: "He shall enter into peace: they shall rest in their beds, each one walking in his uprightness.", versionAbbreviation: "KJV" },
  { dayOfYear: 170, reference: "Psalm 127:2", text: "It is vain for you to rise up early, to sit up late, to eat the bread of sorrows: for so he giveth his beloved sleep.", versionAbbreviation: "KJV" },
  { dayOfYear: 171, reference: "Hebrews 4:9-10", text: "There remaineth therefore a rest to the people of God. For he that is entered into his rest, he also hath ceased from his own works, as God did from his.", versionAbbreviation: "KJV" },
  { dayOfYear: 172, reference: "Psalm 116:7", text: "Return unto thy rest, O my soul; for the LORD hath dealt bountifully with thee.", versionAbbreviation: "KJV" },
  { dayOfYear: 173, reference: "Exodus 33:14", text: "And he said, My presence shall go with thee, and I will give thee rest.", versionAbbreviation: "KJV" },
  { dayOfYear: 174, reference: "Psalm 131:2", text: "Surely I have behaved and quieted myself, as a child that is weaned of his mother: my soul is even as a weaned child.", versionAbbreviation: "KJV" },
  { dayOfYear: 175, reference: "Matthew 6:34", text: "Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself. Sufficient unto the day is the evil thereof.", versionAbbreviation: "KJV" },
  { dayOfYear: 176, reference: "Psalm 94:19", text: "In the multitude of my thoughts within me thy comforts delight my soul.", versionAbbreviation: "KJV" },
  { dayOfYear: 177, reference: "1 Peter 5:7", text: "Casting all your care upon him; for he careth for you.", versionAbbreviation: "KJV" },
  { dayOfYear: 178, reference: "Psalm 107:29-30", text: "He maketh the storm a calm, so that the waves thereof are still. Then are they glad because they be quiet; so he bringeth them unto their desired haven.", versionAbbreviation: "KJV" },
  { dayOfYear: 179, reference: "Philippians 4:8", text: "Finally, brethren, whatsoever things are true, whatsoever things are honest, whatsoever things are just, whatsoever things are pure, whatsoever things are lovely, whatsoever things are of good report; if there be any virtue, and if there be any praise, think on these things.", versionAbbreviation: "KJV" },
  { dayOfYear: 180, reference: "Psalm 46:10", text: "Be still, and know that I am God: I will be exalted among the heathen, I will be exalted in the earth.", versionAbbreviation: "KJV" },
  { dayOfYear: 181, reference: "Proverbs 14:30", text: "A sound heart is the life of the flesh: but envy the rottenness of the bones.", versionAbbreviation: "KJV" },

  // JULY (Days 182-212) — Faith & Trust
  { dayOfYear: 182, reference: "Hebrews 11:6", text: "But without faith it is impossible to please him: for he that cometh to God must believe that he is, and that he is a rewarder of them that diligently seek him.", versionAbbreviation: "KJV" },
  { dayOfYear: 183, reference: "Mark 11:24", text: "Therefore I say unto you, What things soever ye desire, when ye pray, believe that ye receive them, and ye shall have them.", versionAbbreviation: "KJV" },
  { dayOfYear: 184, reference: "Psalm 56:3-4", text: "What time I am afraid, I will trust in thee. In God I will praise his word, in God I have put my trust; I will not fear what flesh can do unto me.", versionAbbreviation: "KJV" },
  { dayOfYear: 185, reference: "Matthew 17:20", text: "And Jesus said unto them, Because of your unbelief: for verily I say unto you, If ye have faith as a grain of mustard seed, ye shall say unto this mountain, Remove hence to yonder place; and it shall remove; and nothing shall be impossible unto you.", versionAbbreviation: "KJV" },
  { dayOfYear: 186, reference: "Psalm 112:7", text: "He shall not be afraid of evil tidings: his heart is fixed, trusting in the LORD.", versionAbbreviation: "KJV" },
  { dayOfYear: 187, reference: "2 Corinthians 5:7", text: "For we walk by faith, not by sight.", versionAbbreviation: "KJV" },
  { dayOfYear: 188, reference: "Psalm 20:7", text: "Some trust in chariots, and some in horses: but we will remember the name of the LORD our God.", versionAbbreviation: "KJV" },
  { dayOfYear: 189, reference: "Romans 10:17", text: "So then faith cometh by hearing, and hearing by the word of God.", versionAbbreviation: "KJV" },
  { dayOfYear: 190, reference: "Psalm 5:11", text: "But let all those that put their trust in thee rejoice: let them ever shout for joy, because thou defendest them: let them also that love thy name be joyful in thee.", versionAbbreviation: "KJV" },
  { dayOfYear: 191, reference: "1 John 5:4", text: "For whatsoever is born of God overcometh the world: and this is the victory that overcometh the world, even our faith.", versionAbbreviation: "KJV" },
  { dayOfYear: 192, reference: "Psalm 37:5", text: "Commit thy way unto the LORD; trust also in him; and he shall bring it to pass.", versionAbbreviation: "KJV" },
  { dayOfYear: 193, reference: "Galatians 2:20", text: "I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me: and the life which I now live in the flesh I live by the faith of the Son of God, who loved me, and gave himself for me.", versionAbbreviation: "KJV" },
  { dayOfYear: 194, reference: "Psalm 115:11", text: "Ye that fear the LORD, trust in the LORD: he is their help and their shield.", versionAbbreviation: "KJV" },
  { dayOfYear: 195, reference: "Matthew 21:22", text: "And all things, whatsoever ye shall ask in prayer, believing, ye shall receive.", versionAbbreviation: "KJV" },
  { dayOfYear: 196, reference: "Psalm 84:12", text: "O LORD of hosts, blessed is the man that trusteth in thee.", versionAbbreviation: "KJV" },
  { dayOfYear: 197, reference: "Hebrews 11:3", text: "Through faith we understand that the worlds were framed by the word of God, so that things which are seen were not made of things which do appear.", versionAbbreviation: "KJV" },
  { dayOfYear: 198, reference: "Psalm 125:1", text: "They that trust in the LORD shall be as mount Zion, which cannot be removed, but abideth for ever.", versionAbbreviation: "KJV" },
  { dayOfYear: 199, reference: "James 2:17", text: "Even so faith, if it hath not works, is dead, being alone.", versionAbbreviation: "KJV" },
  { dayOfYear: 200, reference: "Proverbs 30:5", text: "Every word of God is pure: he is a shield unto them that put their trust in him.", versionAbbreviation: "KJV" },
  { dayOfYear: 201, reference: "Hebrews 12:2", text: "Looking unto Jesus the author and finisher of our faith; who for the joy that was set before him endured the cross, despising the shame, and is set down at the right hand of the throne of God.", versionAbbreviation: "KJV" },
  { dayOfYear: 202, reference: "Psalm 143:8", text: "Cause me to hear thy lovingkindness in the morning; for in thee do I trust: cause me to know the way wherein I should walk; for I lift up my soul unto thee.", versionAbbreviation: "KJV" },
  { dayOfYear: 203, reference: "1 Corinthians 2:5", text: "That your faith should not stand in the wisdom of men, but in the power of God.", versionAbbreviation: "KJV" },
  { dayOfYear: 204, reference: "Nahum 1:7", text: "The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.", versionAbbreviation: "KJV" },
  { dayOfYear: 205, reference: "Ephesians 6:16", text: "Above all, taking the shield of faith, wherewith ye shall be able to quench all the fiery darts of the wicked.", versionAbbreviation: "KJV" },
  { dayOfYear: 206, reference: "Psalm 13:5", text: "But I have trusted in thy mercy; my heart shall rejoice in thy salvation.", versionAbbreviation: "KJV" },
  { dayOfYear: 207, reference: "Mark 9:23", text: "Jesus said unto him, If thou canst believe, all things are possible to him that believeth.", versionAbbreviation: "KJV" },
  { dayOfYear: 208, reference: "Psalm 40:4", text: "Blessed is that man that maketh the LORD his trust, and respecteth not the proud, nor such as turn aside to lies.", versionAbbreviation: "KJV" },
  { dayOfYear: 209, reference: "Romans 1:17", text: "For therein is the righteousness of God revealed from faith to faith: as it is written, The just shall live by faith.", versionAbbreviation: "KJV" },
  { dayOfYear: 210, reference: "Psalm 52:8", text: "But I am like a green olive tree in the house of God: I trust in the mercy of God for ever and ever.", versionAbbreviation: "KJV" },
  { dayOfYear: 211, reference: "1 Peter 1:8-9", text: "Whom having not seen, ye love; in whom, though now ye see him not, yet believing, ye rejoice with joy unspeakable and full of glory: Receiving the end of your faith, even the salvation of your souls.", versionAbbreviation: "KJV" },
  { dayOfYear: 212, reference: "Psalm 33:21", text: "For our heart shall rejoice in him, because we have trusted in his holy name.", versionAbbreviation: "KJV" },

  // AUGUST (Days 213-243) — Joy & Praise
  { dayOfYear: 213, reference: "Psalm 100:1-2", text: "Make a joyful noise unto the LORD, all ye lands. Serve the LORD with gladness: come before his presence with singing.", versionAbbreviation: "KJV" },
  { dayOfYear: 214, reference: "Nehemiah 8:10", text: "Then he said unto them, Go your way, eat the fat, and drink the sweet, and send portions unto them for whom nothing is prepared: for this day is holy unto our Lord: neither be ye sorry; for the joy of the LORD is your strength.", versionAbbreviation: "KJV" },
  { dayOfYear: 215, reference: "Psalm 30:5", text: "For his anger endureth but a moment; in his favour is life: weeping may endure for a night, but joy cometh in the morning.", versionAbbreviation: "KJV" },
  { dayOfYear: 216, reference: "James 1:2-3", text: "My brethren, count it all joy when ye fall into divers temptations; Knowing this, that the trying of your faith worketh patience.", versionAbbreviation: "KJV" },
  { dayOfYear: 217, reference: "Psalm 149:1", text: "Praise ye the LORD. Sing unto the LORD a new song, and his praise in the congregation of saints.", versionAbbreviation: "KJV" },
  { dayOfYear: 218, reference: "Romans 15:13", text: "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.", versionAbbreviation: "KJV" },
  { dayOfYear: 219, reference: "Psalm 47:1", text: "O clap your hands, all ye people; shout unto God with the voice of triumph.", versionAbbreviation: "KJV" },
  { dayOfYear: 220, reference: "1 Thessalonians 5:16-18", text: "Rejoice evermore. Pray without ceasing. In every thing give thanks: for this is the will of God in Christ Jesus concerning you.", versionAbbreviation: "KJV" },
  { dayOfYear: 221, reference: "Psalm 95:1-2", text: "O come, let us sing unto the LORD: let us make a joyful noise to the rock of our salvation. Let us come before his presence with thanksgiving, and make a joyful noise unto him with psalms.", versionAbbreviation: "KJV" },
  { dayOfYear: 222, reference: "John 15:11", text: "These things have I spoken unto you, that my joy might remain in you, and that your joy might be full.", versionAbbreviation: "KJV" },
  { dayOfYear: 223, reference: "Psalm 150:6", text: "Let every thing that hath breath praise the LORD. Praise ye the LORD.", versionAbbreviation: "KJV" },
  { dayOfYear: 224, reference: "Philippians 4:4", text: "Rejoice in the Lord alway: and again I say, Rejoice.", versionAbbreviation: "KJV" },
  { dayOfYear: 225, reference: "Psalm 34:1", text: "I will bless the LORD at all times: his praise shall continually be in my mouth.", versionAbbreviation: "KJV" },
  { dayOfYear: 226, reference: "Habakkuk 3:17-18", text: "Although the fig tree shall not blossom, neither shall fruit be in the vines; the labour of the olive shall fail, and the fields shall yield no meat; the flock shall be cut off from the fold, and there shall be no herd in the stalls: Yet I will rejoice in the LORD, I will joy in the God of my salvation.", versionAbbreviation: "KJV" },
  { dayOfYear: 227, reference: "Psalm 63:3-4", text: "Because thy lovingkindness is better than life, my lips shall praise thee. Thus will I bless thee while I live: I will lift up my hands in thy name.", versionAbbreviation: "KJV" },
  { dayOfYear: 228, reference: "Isaiah 61:10", text: "I will greatly rejoice in the LORD, my soul shall be joyful in my God; for he hath clothed me with the garments of salvation, he hath covered me with the robe of righteousness, as a bridegroom decketh himself with ornaments, and as a bride adorneth herself with her jewels.", versionAbbreviation: "KJV" },
  { dayOfYear: 229, reference: "Psalm 103:1", text: "Bless the LORD, O my soul: and all that is within me, bless his holy name.", versionAbbreviation: "KJV" },
  { dayOfYear: 230, reference: "Acts 2:28", text: "Thou hast made known to me the ways of life; thou shalt make me full of joy with thy countenance.", versionAbbreviation: "KJV" },
  { dayOfYear: 231, reference: "Psalm 145:1-2", text: "I will extol thee, my God, O king; and I will bless thy name for ever and ever. Every day will I bless thee; and I will praise thy name for ever and ever.", versionAbbreviation: "KJV" },
  { dayOfYear: 232, reference: "Galatians 5:22", text: "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith,", versionAbbreviation: "KJV" },
  { dayOfYear: 233, reference: "Psalm 98:4", text: "Make a joyful noise unto the LORD, all the earth: make a loud noise, and rejoice, and sing praise.", versionAbbreviation: "KJV" },
  { dayOfYear: 234, reference: "John 16:24", text: "Hitherto have ye asked nothing in my name: ask, and ye shall receive, that your joy may be full.", versionAbbreviation: "KJV" },
  { dayOfYear: 235, reference: "Psalm 19:14", text: "Let the words of my mouth, and the meditation of my heart, be acceptable in thy sight, O LORD, my strength, and my redeemer.", versionAbbreviation: "KJV" },
  { dayOfYear: 236, reference: "Romans 12:12", text: "Rejoicing in hope; patient in tribulation; continuing instant in prayer;", versionAbbreviation: "KJV" },
  { dayOfYear: 237, reference: "Psalm 113:3", text: "From the rising of the sun unto the going down of the same the LORD's name is to be praised.", versionAbbreviation: "KJV" },
  { dayOfYear: 238, reference: "1 Peter 1:6", text: "Wherein ye greatly rejoice, though now for a season, if need be, ye are in heaviness through manifold temptations:", versionAbbreviation: "KJV" },
  { dayOfYear: 239, reference: "Psalm 66:1-2", text: "Make a joyful noise unto God, all ye lands: Sing forth the honour of his name: make his praise glorious.", versionAbbreviation: "KJV" },
  { dayOfYear: 240, reference: "Psalm 118:24", text: "This is the day which the LORD hath made; we will rejoice and be glad in it.", versionAbbreviation: "KJV" },
  { dayOfYear: 241, reference: "Isaiah 12:5-6", text: "Sing unto the LORD; for he hath done excellent things: this is known in all the earth. Cry out and shout, thou inhabitant of Zion: for great is the Holy One of Israel in the midst of thee.", versionAbbreviation: "KJV" },
  { dayOfYear: 242, reference: "Psalm 96:1", text: "O sing unto the LORD a new song: sing unto the LORD, all the earth.", versionAbbreviation: "KJV" },
  { dayOfYear: 243, reference: "Psalm 9:2", text: "I will be glad and rejoice in thee: I will sing praise to thy name, O thou most High.", versionAbbreviation: "KJV" },

  // SEPTEMBER (Days 244-273) — Prayer & Devotion
  { dayOfYear: 244, reference: "Jeremiah 33:3", text: "Call unto me, and I will answer thee, and shew thee great and mighty things, which thou knowest not.", versionAbbreviation: "KJV" },
  { dayOfYear: 245, reference: "1 John 5:14", text: "And this is the confidence that we have in him, that, if we ask any thing according to his will, he heareth us:", versionAbbreviation: "KJV" },
  { dayOfYear: 246, reference: "Psalm 145:18", text: "The LORD is nigh unto all them that call upon him, to all that call upon him in truth.", versionAbbreviation: "KJV" },
  { dayOfYear: 247, reference: "Matthew 7:7", text: "Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you:", versionAbbreviation: "KJV" },
  { dayOfYear: 248, reference: "Psalm 141:2", text: "Let my prayer be set forth before thee as incense; and the lifting up of my hands as the evening sacrifice.", versionAbbreviation: "KJV" },
  { dayOfYear: 249, reference: "James 5:16", text: "Confess your faults one to another, and pray one for another, that ye may be healed. The effectual fervent prayer of a righteous man availeth much.", versionAbbreviation: "KJV" },
  { dayOfYear: 250, reference: "Psalm 17:6", text: "I have called upon thee, for thou wilt hear me, O God: incline thine ear unto me, and hear my speech.", versionAbbreviation: "KJV" },
  { dayOfYear: 251, reference: "Philippians 4:6", text: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.", versionAbbreviation: "KJV" },
  { dayOfYear: 252, reference: "Psalm 86:6-7", text: "Give ear, O LORD, unto my prayer; and attend to the voice of my supplications. In the day of my trouble I will call upon thee: for thou wilt answer me.", versionAbbreviation: "KJV" },
  { dayOfYear: 253, reference: "1 Thessalonians 5:17", text: "Pray without ceasing.", versionAbbreviation: "KJV" },
  { dayOfYear: 254, reference: "Psalm 65:2", text: "O thou that hearest prayer, unto thee shall all flesh come.", versionAbbreviation: "KJV" },
  { dayOfYear: 255, reference: "Matthew 6:6", text: "But thou, when thou prayest, enter into thy closet, and when thou hast shut thy door, pray to thy Father which is in secret; and thy Father which seeth in secret shall reward thee openly.", versionAbbreviation: "KJV" },
  { dayOfYear: 256, reference: "Psalm 102:17", text: "He will regard the prayer of the destitute, and not despise their prayer.", versionAbbreviation: "KJV" },
  { dayOfYear: 257, reference: "Romans 8:26", text: "Likewise the Spirit also helpeth our infirmities: for we know not what we should pray for as we ought: but the Spirit itself maketh intercession for us with groanings which cannot be uttered.", versionAbbreviation: "KJV" },
  { dayOfYear: 258, reference: "Psalm 55:17", text: "Evening, and morning, and at noon, will I pray, and cry aloud: and he shall hear my voice.", versionAbbreviation: "KJV" },
  { dayOfYear: 259, reference: "Colossians 4:2", text: "Continue in prayer, and watch in the same with thanksgiving;", versionAbbreviation: "KJV" },
  { dayOfYear: 260, reference: "Psalm 5:3", text: "My voice shalt thou hear in the morning, O LORD; in the morning will I direct my prayer unto thee, and will look up.", versionAbbreviation: "KJV" },
  { dayOfYear: 261, reference: "Luke 11:9", text: "And I say unto you, Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you.", versionAbbreviation: "KJV" },
  { dayOfYear: 262, reference: "Psalm 66:19-20", text: "But verily God hath heard me; he hath attended to the voice of my prayer. Blessed be God, which hath not turned away my prayer, nor his mercy from me.", versionAbbreviation: "KJV" },
  { dayOfYear: 263, reference: "Ephesians 6:18", text: "Praying always with all prayer and supplication in the Spirit, and watching thereunto with all perseverance and supplication for all saints;", versionAbbreviation: "KJV" },
  { dayOfYear: 264, reference: "Psalm 42:1-2", text: "As the deer panteth after the water brooks, so panteth my soul after thee, O God. My soul thirsteth for God, for the living God: when shall I come and appear before God?", versionAbbreviation: "KJV" },
  { dayOfYear: 265, reference: "2 Chronicles 7:14", text: "If my people, which are called by my name, shall humble themselves, and pray, and seek my face, and turn from their wicked ways; then will I hear from heaven, and will forgive their sin, and will heal their land.", versionAbbreviation: "KJV" },
  { dayOfYear: 266, reference: "Psalm 63:1", text: "O God, thou art my God; early will I seek thee: my soul thirsteth for thee, my flesh longeth for thee in a dry and thirsty land, where no water is;", versionAbbreviation: "KJV" },
  { dayOfYear: 267, reference: "Matthew 18:20", text: "For where two or three are gathered together in my name, there am I in the midst of them.", versionAbbreviation: "KJV" },
  { dayOfYear: 268, reference: "Psalm 27:4", text: "One thing have I desired of the LORD, that will I seek after; that I may dwell in the house of the LORD all the days of my life, to behold the beauty of the LORD, and to enquire in his temple.", versionAbbreviation: "KJV" },
  { dayOfYear: 269, reference: "Hebrews 4:16", text: "Let us therefore come boldly unto the throne of grace, that we may obtain mercy, and find grace to help in time of need.", versionAbbreviation: "KJV" },
  { dayOfYear: 270, reference: "Psalm 73:28", text: "But it is good for me to draw near to God: I have put my trust in the Lord GOD, that I may declare all thy works.", versionAbbreviation: "KJV" },
  { dayOfYear: 271, reference: "John 15:7", text: "If ye abide in me, and my words abide in you, ye shall ask what ye will, and it shall be done unto you.", versionAbbreviation: "KJV" },
  { dayOfYear: 272, reference: "Psalm 105:4", text: "Seek the LORD, and his strength: seek his face evermore.", versionAbbreviation: "KJV" },
  { dayOfYear: 273, reference: "1 John 5:15", text: "And if we know that he hear us, whatsoever we ask, we know that we have the petitions that we desired of him.", versionAbbreviation: "KJV" },

  // OCTOBER (Days 274-304) — God's Word & Truth
  { dayOfYear: 274, reference: "2 Timothy 3:16-17", text: "All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness: That the man of God may be perfect, throughly furnished unto all good works.", versionAbbreviation: "KJV" },
  { dayOfYear: 275, reference: "Psalm 119:11", text: "Thy word have I hid in mine heart, that I might not sin against thee.", versionAbbreviation: "KJV" },
  { dayOfYear: 276, reference: "Isaiah 40:8", text: "The grass withereth, the flower fadeth: but the word of our God shall stand for ever.", versionAbbreviation: "KJV" },
  { dayOfYear: 277, reference: "Psalm 119:130", text: "The entrance of thy words giveth light; it giveth understanding unto the simple.", versionAbbreviation: "KJV" },
  { dayOfYear: 278, reference: "Hebrews 4:12", text: "For the word of God is quick, and powerful, and sharper than any twoedged sword, piercing even to the dividing asunder of soul and spirit, and of the joints and marrow, and is a discerner of the thoughts and intents of the heart.", versionAbbreviation: "KJV" },
  { dayOfYear: 279, reference: "Psalm 19:7", text: "The law of the LORD is perfect, converting the soul: the testimony of the LORD is sure, making wise the simple.", versionAbbreviation: "KJV" },
  { dayOfYear: 280, reference: "John 17:17", text: "Sanctify them through thy truth: thy word is truth.", versionAbbreviation: "KJV" },
  { dayOfYear: 281, reference: "Psalm 119:89", text: "For ever, O LORD, thy word is settled in heaven.", versionAbbreviation: "KJV" },
  { dayOfYear: 282, reference: "Matthew 4:4", text: "But he answered and said, It is written, Man shall not live by bread alone, but by every word that proceedeth out of the mouth of God.", versionAbbreviation: "KJV" },
  { dayOfYear: 283, reference: "Psalm 119:160", text: "Thy word is true from the beginning: and every one of thy righteous judgments endureth for ever.", versionAbbreviation: "KJV" },
  { dayOfYear: 284, reference: "John 8:32", text: "And ye shall know the truth, and the truth shall make you free.", versionAbbreviation: "KJV" },
  { dayOfYear: 285, reference: "Psalm 33:4", text: "For the word of the LORD is right; and all his works are done in truth.", versionAbbreviation: "KJV" },
  { dayOfYear: 286, reference: "Joshua 1:8", text: "This book of the law shall not depart out of thy mouth; but thou shalt meditate therein day and night, that thou mayest observe to do according to all that is written therein: for then thou shalt make thy way prosperous, and then thou shalt have good success.", versionAbbreviation: "KJV" },
  { dayOfYear: 287, reference: "Psalm 119:103", text: "How sweet are thy words unto my taste! yea, sweeter than honey to my mouth!", versionAbbreviation: "KJV" },
  { dayOfYear: 288, reference: "John 1:1", text: "In the beginning was the Word, and the Word was with God, and the Word was God.", versionAbbreviation: "KJV" },
  { dayOfYear: 289, reference: "Psalm 1:2-3", text: "But his delight is in the law of the LORD; and in his law doth he meditate day and night. And he shall be like a tree planted by the rivers of water, that bringeth forth his fruit in his season; his leaf also shall not wither; and whatsoever he doeth shall prosper.", versionAbbreviation: "KJV" },
  { dayOfYear: 290, reference: "Romans 10:17", text: "So then faith cometh by hearing, and hearing by the word of God.", versionAbbreviation: "KJV" },
  { dayOfYear: 291, reference: "Psalm 119:9", text: "Wherewithal shall a young man cleanse his way? by taking heed thereto according to thy word.", versionAbbreviation: "KJV" },
  { dayOfYear: 292, reference: "Colossians 3:16", text: "Let the word of Christ dwell in you richly in all wisdom; teaching and admonishing one another in psalms and hymns and spiritual songs, singing with grace in your hearts to the Lord.", versionAbbreviation: "KJV" },
  { dayOfYear: 293, reference: "Psalm 119:50", text: "This is my comfort in my affliction: for thy word hath quickened me.", versionAbbreviation: "KJV" },
  { dayOfYear: 294, reference: "1 Peter 1:25", text: "But the word of the Lord endureth for ever. And this is the word which by the gospel is preached unto you.", versionAbbreviation: "KJV" },
  { dayOfYear: 295, reference: "Psalm 119:105", text: "Thy word is a lamp unto my feet, and a light unto my path.", versionAbbreviation: "KJV" },
  { dayOfYear: 296, reference: "John 6:63", text: "It is the spirit that quickeneth; the flesh profiteth nothing: the words that I speak unto you, they are spirit, and they are life.", versionAbbreviation: "KJV" },
  { dayOfYear: 297, reference: "Psalm 119:72", text: "The law of thy mouth is better unto me than thousands of gold and silver.", versionAbbreviation: "KJV" },
  { dayOfYear: 298, reference: "Matthew 24:35", text: "Heaven and earth shall pass away, but my words shall not pass away.", versionAbbreviation: "KJV" },
  { dayOfYear: 299, reference: "Psalm 119:24", text: "Thy testimonies also are my delight and my counsellors.", versionAbbreviation: "KJV" },
  { dayOfYear: 300, reference: "James 1:22", text: "But be ye doers of the word, and not hearers only, deceiving your own selves.", versionAbbreviation: "KJV" },
  { dayOfYear: 301, reference: "Psalm 12:6", text: "The words of the LORD are pure words: as silver tried in a furnace of earth, purified seven times.", versionAbbreviation: "KJV" },
  { dayOfYear: 302, reference: "Proverbs 30:5", text: "Every word of God is pure: he is a shield unto them that put their trust in him.", versionAbbreviation: "KJV" },
  { dayOfYear: 303, reference: "Psalm 119:162", text: "I rejoice at thy word, as one that findeth great spoil.", versionAbbreviation: "KJV" },
  { dayOfYear: 304, reference: "John 14:6", text: "Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me.", versionAbbreviation: "KJV" },

  // NOVEMBER (Days 305-334) — Gratitude & Provision
  { dayOfYear: 305, reference: "Psalm 107:1", text: "O give thanks unto the LORD, for he is good: for his mercy endureth for ever.", versionAbbreviation: "KJV" },
  { dayOfYear: 306, reference: "Colossians 3:17", text: "And whatsoever ye do in word or deed, do all in the name of the Lord Jesus, giving thanks to God and the Father by him.", versionAbbreviation: "KJV" },
  { dayOfYear: 307, reference: "Psalm 103:2-3", text: "Bless the LORD, O my soul, and forget not all his benefits: Who forgiveth all thine iniquities; who healeth all thy diseases;", versionAbbreviation: "KJV" },
  { dayOfYear: 308, reference: "1 Chronicles 16:34", text: "O give thanks unto the LORD; for he is good; for his mercy endureth for ever.", versionAbbreviation: "KJV" },
  { dayOfYear: 309, reference: "Psalm 136:26", text: "O give thanks unto the God of heaven: for his mercy endureth for ever.", versionAbbreviation: "KJV" },
  { dayOfYear: 310, reference: "Ephesians 5:20", text: "Giving thanks always for all things unto God and the Father in the name of our Lord Jesus Christ;", versionAbbreviation: "KJV" },
  { dayOfYear: 311, reference: "Psalm 50:14", text: "Offer unto God thanksgiving; and pay thy vows unto the most High:", versionAbbreviation: "KJV" },
  { dayOfYear: 312, reference: "Matthew 6:31-32", text: "Therefore take no thought, saying, What shall we eat? or, What shall we drink? or, Wherewithal shall we be clothed? (For after all these things do the Gentiles seek:) for your heavenly Father knoweth that ye have need of all these things.", versionAbbreviation: "KJV" },
  { dayOfYear: 313, reference: "Psalm 100:4", text: "Enter into his gates with thanksgiving, and into his courts with praise: be thankful unto him, and bless his name.", versionAbbreviation: "KJV" },
  { dayOfYear: 314, reference: "Philippians 4:19", text: "But my God shall supply all your need according to his riches in glory by Christ Jesus.", versionAbbreviation: "KJV" },
  { dayOfYear: 315, reference: "Psalm 116:12", text: "What shall I render unto the LORD for all his benefits toward me?", versionAbbreviation: "KJV" },
  { dayOfYear: 316, reference: "James 1:17", text: "Every good gift and every perfect gift is from above, and cometh down from the Father of lights, with whom is no variableness, neither shadow of turning.", versionAbbreviation: "KJV" },
  { dayOfYear: 317, reference: "Psalm 68:19", text: "Blessed be the Lord, who daily loadeth us with benefits, even the God of our salvation.", versionAbbreviation: "KJV" },
  { dayOfYear: 318, reference: "2 Corinthians 9:8", text: "And God is able to make all grace abound toward you; that ye, always having all sufficiency in all things, may abound to every good work:", versionAbbreviation: "KJV" },
  { dayOfYear: 319, reference: "Psalm 111:1", text: "Praise ye the LORD. I will praise the LORD with my whole heart, in the assembly of the upright, and in the congregation.", versionAbbreviation: "KJV" },
  { dayOfYear: 320, reference: "Luke 6:38", text: "Give, and it shall be given unto you; good measure, pressed down, and shaken together, and running over, shall men give into your bosom. For with the same measure that ye mete withal it shall be measured to you again.", versionAbbreviation: "KJV" },
  { dayOfYear: 321, reference: "Psalm 92:1-2", text: "It is a good thing to give thanks unto the LORD, and to sing praises unto thy name, O most High: To shew forth thy lovingkindness in the morning, and thy faithfulness every night,", versionAbbreviation: "KJV" },
  { dayOfYear: 322, reference: "Malachi 3:10", text: "Bring ye all the tithes into the storehouse, that there may be meat in mine house, and prove me now herewith, saith the LORD of hosts, if I will not open you the windows of heaven, and pour you out a blessing, that there shall not be room enough to receive it.", versionAbbreviation: "KJV" },
  { dayOfYear: 323, reference: "Psalm 107:8-9", text: "Oh that men would praise the LORD for his goodness, and for his wonderful works to the children of men! For he satisfieth the longing soul, and filleth the hungry soul with goodness.", versionAbbreviation: "KJV" },
  { dayOfYear: 324, reference: "Deuteronomy 8:18", text: "But thou shalt remember the LORD thy God: for it is he that giveth thee power to get wealth, that he may establish his covenant which he sware unto thy fathers, as it is this day.", versionAbbreviation: "KJV" },
  { dayOfYear: 325, reference: "Psalm 104:24", text: "O LORD, how manifold are thy works! in wisdom hast thou made them all: the earth is full of thy riches.", versionAbbreviation: "KJV" },
  { dayOfYear: 326, reference: "2 Corinthians 9:15", text: "Thanks be unto God for his unspeakable gift.", versionAbbreviation: "KJV" },
  { dayOfYear: 327, reference: "Psalm 34:10", text: "The young lions do lack, and suffer hunger: but they that seek the LORD shall not want any good thing.", versionAbbreviation: "KJV" },
  { dayOfYear: 328, reference: "Proverbs 10:22", text: "The blessing of the LORD, it maketh rich, and he addeth no sorrow with it.", versionAbbreviation: "KJV" },
  { dayOfYear: 329, reference: "Psalm 65:11", text: "Thou crownest the year with thy goodness; and thy paths drop fatness.", versionAbbreviation: "KJV" },
  { dayOfYear: 330, reference: "Matthew 7:11", text: "If ye then, being evil, know how to give good gifts unto your children, how much more shall your Father which is in heaven give good things to them that ask him?", versionAbbreviation: "KJV" },
  { dayOfYear: 331, reference: "Psalm 37:25", text: "I have been young, and now am old; yet have I not seen the righteous forsaken, nor his seed begging bread.", versionAbbreviation: "KJV" },
  { dayOfYear: 332, reference: "Genesis 22:14", text: "And Abraham called the name of that place Jehovahjireh: as it is said to this day, In the mount of the LORD it shall be seen.", versionAbbreviation: "KJV" },
  { dayOfYear: 333, reference: "Psalm 23:5", text: "Thou preparest a table before me in the presence of mine enemies: thou anointest my head with oil; my cup runneth over.", versionAbbreviation: "KJV" },
  { dayOfYear: 334, reference: "Psalm 145:15-16", text: "The eyes of all wait upon thee; and thou givest them their meat in due season. Thou openest thine hand, and satisfiest the desire of every living thing.", versionAbbreviation: "KJV" },

  // DECEMBER (Days 335-366) — Salvation, Eternity & Advent
  { dayOfYear: 335, reference: "John 3:16", text: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.", versionAbbreviation: "KJV" },
  { dayOfYear: 336, reference: "Romans 6:23", text: "For the wages of sin is death; but the gift of God is eternal life through Jesus Christ our Lord.", versionAbbreviation: "KJV" },
  { dayOfYear: 337, reference: "Ephesians 2:4-5", text: "But God, who is rich in mercy, for his great love wherewith he loved us, Even when we were dead in sins, hath quickened us together with Christ, (by grace ye are saved;)", versionAbbreviation: "KJV" },
  { dayOfYear: 338, reference: "Titus 2:11", text: "For the grace of God that bringeth salvation hath appeared to all men,", versionAbbreviation: "KJV" },
  { dayOfYear: 339, reference: "Acts 4:12", text: "Neither is there salvation in any other: for there is none other name under heaven given among men, whereby we must be saved.", versionAbbreviation: "KJV" },
  { dayOfYear: 340, reference: "1 John 5:11-12", text: "And this is the record, that God hath given to us eternal life, and this life is in his Son. He that hath the Son hath life; and he that hath not the Son of God hath not life.", versionAbbreviation: "KJV" },
  { dayOfYear: 341, reference: "John 10:28", text: "And I give unto them eternal life; and they shall never perish, neither shall any man pluck them out of my hand.", versionAbbreviation: "KJV" },
  { dayOfYear: 342, reference: "2 Corinthians 5:17", text: "Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.", versionAbbreviation: "KJV" },
  { dayOfYear: 343, reference: "Romans 10:9", text: "That if thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be saved.", versionAbbreviation: "KJV" },
  { dayOfYear: 344, reference: "John 14:2-3", text: "In my Father's house are many mansions: if it were not so, I would have told you. I go to prepare a place for you. And if I go and prepare a place for you, I will come again, and receive you unto myself; that where I am, there ye may be also.", versionAbbreviation: "KJV" },
  { dayOfYear: 345, reference: "1 Corinthians 15:55-57", text: "O death, where is thy sting? O grave, where is thy victory? The sting of death is sin; and the strength of sin is the law. But thanks be to God, which giveth us the victory through our Lord Jesus Christ.", versionAbbreviation: "KJV" },
  { dayOfYear: 346, reference: "Revelation 22:20", text: "He which testifieth these things saith, Surely I come quickly. Amen. Even so, come, Lord Jesus.", versionAbbreviation: "KJV" },
  { dayOfYear: 347, reference: "John 11:25-26", text: "Jesus said unto her, I am the resurrection, and the life: he that believeth in me, though he were dead, yet shall he live: And whosoever liveth and believeth in me shall never die. Believest thou this?", versionAbbreviation: "KJV" },
  { dayOfYear: 348, reference: "Romans 8:1", text: "There is therefore now no condemnation to them which are in Christ Jesus, who walk not after the flesh, but after the Spirit.", versionAbbreviation: "KJV" },
  { dayOfYear: 349, reference: "1 Peter 1:3-4", text: "Blessed be the God and Father of our Lord Jesus Christ, which according to his abundant mercy hath begotten us again unto a lively hope by the resurrection of Jesus Christ from the dead, To an inheritance incorruptible, and undefiled, and that fadeth not away, reserved in heaven for you,", versionAbbreviation: "KJV" },
  { dayOfYear: 350, reference: "John 5:24", text: "Verily, verily, I say unto you, He that heareth my word, and believeth on him that sent me, hath everlasting life, and shall not come into condemnation; but is passed from death unto life.", versionAbbreviation: "KJV" },
  { dayOfYear: 351, reference: "Isaiah 9:6", text: "For unto us a child is born, unto us a son is given: and the government shall be upon his shoulder: and his name shall be called Wonderful, Counsellor, The mighty God, The everlasting Father, The Prince of Peace.", versionAbbreviation: "KJV" },
  { dayOfYear: 352, reference: "Micah 5:2", text: "But thou, Bethlehem Ephratah, though thou be little among the thousands of Judah, yet out of thee shall he come forth unto me that is to be ruler in Israel; whose goings forth have been from of old, from everlasting.", versionAbbreviation: "KJV" },
  { dayOfYear: 353, reference: "Isaiah 7:14", text: "Therefore the Lord himself shall give you a sign; Behold, a virgin shall conceive, and bear a son, and shall call his name Immanuel.", versionAbbreviation: "KJV" },
  { dayOfYear: 354, reference: "Luke 1:46-47", text: "And Mary said, My soul doth magnify the Lord, And my spirit hath rejoiced in God my Saviour.", versionAbbreviation: "KJV" },
  { dayOfYear: 355, reference: "Matthew 1:23", text: "Behold, a virgin shall be with child, and shall bring forth a son, and they shall call his name Emmanuel, which being interpreted is, God with us.", versionAbbreviation: "KJV" },
  { dayOfYear: 356, reference: "Luke 2:10-11", text: "And the angel said unto them, Fear not: for, behold, I bring you good tidings of great joy, which shall be to all people. For unto you is born this day in the city of David a Saviour, which is Christ the Lord.", versionAbbreviation: "KJV" },
  { dayOfYear: 357, reference: "Isaiah 11:1-2", text: "And there shall come forth a rod out of the stem of Jesse, and a Branch shall grow out of his roots: And the spirit of the LORD shall rest upon him, the spirit of wisdom and understanding, the spirit of counsel and might, the spirit of knowledge and of the fear of the LORD;", versionAbbreviation: "KJV" },
  { dayOfYear: 358, reference: "Luke 1:78-79", text: "Through the tender mercy of our God; whereby the dayspring from on high hath visited us, To give light to them that sit in darkness and in the shadow of death, to guide our feet into the way of peace.", versionAbbreviation: "KJV" },
  { dayOfYear: 359, reference: "John 1:14", text: "And the Word was made flesh, and dwelt among us, (and we beheld his glory, the glory as of the only begotten of the Father,) full of grace and truth.", versionAbbreviation: "KJV" },
  { dayOfYear: 360, reference: "Luke 2:14", text: "Glory to God in the highest, and on earth peace, good will toward men.", versionAbbreviation: "KJV" },
  { dayOfYear: 361, reference: "Matthew 2:10-11", text: "When they saw the star, they rejoiced with exceeding great joy. And when they were come into the house, they saw the young child with Mary his mother, and fell down, and worshipped him: and when they had opened their treasures, they presented unto him gifts; gold, and frankincense, and myrrh.", versionAbbreviation: "KJV" },
  { dayOfYear: 362, reference: "Galatians 4:4-5", text: "But when the fulness of the time was come, God sent forth his Son, made of a woman, made under the law, To redeem them that were under the law, that we might receive the adoption of sons.", versionAbbreviation: "KJV" },
  { dayOfYear: 363, reference: "Philippians 2:9-11", text: "Wherefore God also hath highly exalted him, and given him a name which is above every name: That at the name of Jesus every knee should bow, of things in heaven, and things in earth, and things under the earth; And that every tongue should confess that Jesus Christ is Lord, to the glory of God the Father.", versionAbbreviation: "KJV" },
  { dayOfYear: 364, reference: "Revelation 21:5", text: "And he that sat upon the throne said, Behold, I make all things new. And he said unto me, Write: for these words are true and faithful.", versionAbbreviation: "KJV" },
  { dayOfYear: 365, reference: "Psalm 90:12", text: "So teach us to number our days, that we may apply our hearts unto wisdom.", versionAbbreviation: "KJV" },
  { dayOfYear: 366, reference: "Revelation 22:21", text: "The grace of our Lord Jesus Christ be with you all. Amen.", versionAbbreviation: "KJV" },
];

/**
 * Seed the daily_verses table with 366 curated verses.
 * Clears existing entries first, then inserts all verses.
 */
export async function seedDailyVerses(): Promise<void> {
  console.log("Clearing existing daily verses...");
  await db.delete(dailyVerses);

  console.log(`Inserting ${DAILY_VERSES.length} daily verses...`);

  // Insert in batches of 50 for efficiency
  const BATCH_SIZE = 50;
  for (let i = 0; i < DAILY_VERSES.length; i += BATCH_SIZE) {
    const batch = DAILY_VERSES.slice(i, i + BATCH_SIZE);
    await db.insert(dailyVerses).values(batch);
  }

  console.log(`Seeded ${DAILY_VERSES.length} daily verses successfully.`);
}
